""" Contains all the data models used in inputs/outputs """

from .api_add_single_test_job_response import ApiAddSingleTestJobResponse
from .api_add_single_test_step_response import ApiAddSingleTestStepResponse
from .api_agent_base import ApiAgentBase
from .api_agent_create_copy_single_agent import ApiAgentCreateCopySingleAgent
from .api_agent_create_operation import ApiAgentCreateOperation
from .api_agent_create_pool import ApiAgentCreatePool
from .api_agent_create_single_agent import ApiAgentCreateSingleAgent
from .api_agent_execution_status import ApiAgentExecutionStatus
from .api_agent_id_and_name import ApiAgentIdAndName
from .api_agent_patch_operation import ApiAgentPatchOperation
from .api_agent_patch_update_pool import ApiAgentPatchUpdatePool
from .api_agent_patch_update_single_agent import ApiAgentPatchUpdateSingleAgent
from .api_agent_simple_status import ApiAgentSimpleStatus
from .api_agile_backlog import ApiAgileBacklog
from .api_agile_backlog_status import ApiAgileBacklogStatus
from .api_agile_reorder_items_request import ApiAgileReorderItemsRequest
from .api_agile_reorder_items_response import ApiAgileReorderItemsResponse
from .api_agile_reorder_items_response_reordered_priority import ApiAgileReorderItemsResponseReorderedPriority
from .api_agile_settings import ApiAgileSettings
from .api_allowed_option import ApiAllowedOption
from .api_aqua_client_type import ApiAquaClientType
from .api_argument_error import ApiArgumentError
from .api_argument_error_type import ApiArgumentErrorType
from .api_attachment_info import ApiAttachmentInfo
from .api_attachment_new import ApiAttachmentNew
from .api_attachments import ApiAttachments
from .api_automated_test_case_execution import ApiAutomatedTestCaseExecution
from .api_automated_test_scenario_execution_request import ApiAutomatedTestScenarioExecutionRequest
from .api_automated_test_scenario_execution_request_all import ApiAutomatedTestScenarioExecutionRequestAll
from .api_automated_test_scenario_execution_request_partial import ApiAutomatedTestScenarioExecutionRequestPartial
from .api_automated_test_scenario_execution_response import ApiAutomatedTestScenarioExecutionResponse
from .api_automatic_execution_support import ApiAutomaticExecutionSupport
from .api_automation import ApiAutomation
from .api_automation_attached_script_file_info import ApiAutomationAttachedScriptFileInfo
from .api_automation_attached_script_file_new import ApiAutomationAttachedScriptFileNew
from .api_automation_save import ApiAutomationSave
from .api_automation_script import ApiAutomationScript
from .api_automation_script_database import ApiAutomationScriptDatabase
from .api_automation_script_database_save import ApiAutomationScriptDatabaseSave
from .api_automation_script_j_meter import ApiAutomationScriptJMeter
from .api_automation_script_j_meter_save import ApiAutomationScriptJMeterSave
from .api_automation_script_jenkins import ApiAutomationScriptJenkins
from .api_automation_script_jenkins_save import ApiAutomationScriptJenkinsSave
from .api_automation_script_none import ApiAutomationScriptNone
from .api_automation_script_none_save import ApiAutomationScriptNoneSave
from .api_automation_script_not_supported import ApiAutomationScriptNotSupported
from .api_automation_script_not_supported_save import ApiAutomationScriptNotSupportedSave
from .api_automation_script_power_shell import ApiAutomationScriptPowerShell
from .api_automation_script_power_shell_save import ApiAutomationScriptPowerShellSave
from .api_automation_script_qtp import ApiAutomationScriptQTP
from .api_automation_script_qtp_save import ApiAutomationScriptQTPSave
from .api_automation_script_ranorex import ApiAutomationScriptRanorex
from .api_automation_script_ranorex_save import ApiAutomationScriptRanorexSave
from .api_automation_script_save import ApiAutomationScriptSave
from .api_automation_script_shell import ApiAutomationScriptShell
from .api_automation_script_shell_save import ApiAutomationScriptShellSave
from .api_automation_script_soap_ui import ApiAutomationScriptSoapUI
from .api_automation_script_soap_ui_save import ApiAutomationScriptSoapUISave
from .api_automation_script_uft import ApiAutomationScriptUFT
from .api_automation_script_uft_save import ApiAutomationScriptUFTSave
from .api_automation_script_unix_shell import ApiAutomationScriptUnixShell
from .api_automation_script_unix_shell_save import ApiAutomationScriptUnixShellSave
from .api_automation_script_with_attached_files import ApiAutomationScriptWithAttachedFiles
from .api_automation_script_with_attached_files_save import ApiAutomationScriptWithAttachedFilesSave
from .api_automation_technology import ApiAutomationTechnology
from .api_backend_not_available_error import ApiBackendNotAvailableError
from .api_base_item_accessibility import ApiBaseItemAccessibility
from .api_base_object_report_allowed_options import ApiBaseObjectReportAllowedOptions
from .api_base_object_report_allowed_options_update import ApiBaseObjectReportAllowedOptionsUpdate
from .api_base_object_report_options import ApiBaseObjectReportOptions
from .api_batch_allowed_values_request import ApiBatchAllowedValuesRequest
from .api_batch_allowed_values_response import ApiBatchAllowedValuesResponse
from .api_batch_allowed_values_response_entry import ApiBatchAllowedValuesResponseEntry
from .api_batch_field_update import ApiBatchFieldUpdate
from .api_batch_field_update_multi_choice_field_differential import ApiBatchFieldUpdateMultiChoiceFieldDifferential
from .api_batch_field_update_new_enclosure import ApiBatchFieldUpdateNewEnclosure
from .api_batch_field_update_regular_field import ApiBatchFieldUpdateRegularField
from .api_batch_item_operation_issue import ApiBatchItemOperationIssue
from .api_batch_item_operation_issue_type import ApiBatchItemOperationIssueType
from .api_batch_item_update_field_issue_details import ApiBatchItemUpdateFieldIssueDetails
from .api_batch_item_update_issue_details import ApiBatchItemUpdateIssueDetails
from .api_batch_item_update_issue_details_base import ApiBatchItemUpdateIssueDetailsBase
from .api_batch_item_update_issue_details_type import ApiBatchItemUpdateIssueDetailsType
from .api_batch_operation import ApiBatchOperation
from .api_batch_operation_type import ApiBatchOperationType
from .api_bulk_executions_request import ApiBulkExecutionsRequest
from .api_chart_type import ApiChartType
from .api_chart_widget_data import ApiChartWidgetData
from .api_chart_widget_data_one_dimensional_element import ApiChartWidgetDataOneDimensionalElement
from .api_chart_widget_data_specification import ApiChartWidgetDataSpecification
from .api_chart_widget_data_status import ApiChartWidgetDataStatus
from .api_chart_widget_data_two_dimensional_element import ApiChartWidgetDataTwoDimensionalElement
from .api_chart_widget_date_time_scale import ApiChartWidgetDateTimeScale
from .api_chart_widget_kpi_condition import ApiChartWidgetKPICondition
from .api_chart_widget_kpi_entry import ApiChartWidgetKPIEntry
from .api_chart_widget_model import ApiChartWidgetModel
from .api_column_sort_order import ApiColumnSortOrder
from .api_config_element import ApiConfigElement
from .api_config_element_base import ApiConfigElementBase
from .api_config_element_entry import ApiConfigElementEntry
from .api_config_element_entry_save import ApiConfigElementEntrySave
from .api_config_element_patch_operation import ApiConfigElementPatchOperation
from .api_config_element_patch_operation_delete import ApiConfigElementPatchOperationDelete
from .api_config_element_save import ApiConfigElementSave
from .api_create_login_link_response import ApiCreateLoginLinkResponse
from .api_currently_executed_step_info import ApiCurrentlyExecutedStepInfo
from .api_custom_notification_new import ApiCustomNotificationNew
from .api_customized_strings import ApiCustomizedStrings
from .api_customized_strings_english import ApiCustomizedStringsEnglish
from .api_customized_strings_german import ApiCustomizedStringsGerman
from .api_dashboard_ng import ApiDashboardNG
from .api_dashboard_ng_reorder_widgets import ApiDashboardNGReorderWidgets
from .api_dashboard_ng_share_project import ApiDashboardNGShareProject
from .api_dashboard_ng_size import ApiDashboardNGSize
from .api_dashboard_ng_widget import ApiDashboardNGWidget
from .api_dashboard_ng_widget_binding import ApiDashboardNGWidgetBinding
from .api_defect import ApiDefect
from .api_defect_report_allowed_options_update import ApiDefectReportAllowedOptionsUpdate
from .api_defect_report_options import ApiDefectReportOptions
from .api_delete_project_folder_role import ApiDeleteProjectFolderRole
from .api_dependencies_add_permission_patch_response import ApiDependenciesAddPermissionPatchResponse
from .api_dependencies_add_single_permission_patch_request import ApiDependenciesAddSinglePermissionPatchRequest
from .api_dependencies_permission_patch_request import ApiDependenciesPermissionPatchRequest
from .api_dependencies_permission_set_patch_request import ApiDependenciesPermissionSetPatchRequest
from .api_dependencies_permission_set_patch_response import ApiDependenciesPermissionSetPatchResponse
from .api_dependencies_remove_permission_patch_response import ApiDependenciesRemovePermissionPatchResponse
from .api_dependencies_remove_single_permission_patch_request import ApiDependenciesRemoveSinglePermissionPatchRequest
from .api_dependency_type import ApiDependencyType
from .api_diff_category_type import ApiDiffCategoryType
from .api_edit_layout import ApiEditLayout
from .api_edit_layout_entry import ApiEditLayoutEntry
from .api_edit_layout_entry_field import ApiEditLayoutEntryField
from .api_edit_layout_entry_group import ApiEditLayoutEntryGroup
from .api_edit_status import ApiEditStatus
from .api_editable_info import ApiEditableInfo
from .api_editable_status import ApiEditableStatus
from .api_enclosure import ApiEnclosure
from .api_enclosure_permissions import ApiEnclosurePermissions
from .api_enclosure_type import ApiEnclosureType
from .api_enclosure_update import ApiEnclosureUpdate
from .api_enclosure_update_with_id import ApiEnclosureUpdateWithId
from .api_enclosures_update import ApiEnclosuresUpdate
from .api_environment_info import ApiEnvironmentInfo
from .api_error import ApiError
from .api_error_information import ApiErrorInformation
from .api_execution_log_message_type import ApiExecutionLogMessageType
from .api_export_long_running_task_info import ApiExportLongRunningTaskInfo
from .api_external_info import ApiExternalInfo
from .api_feature_info import ApiFeatureInfo
from .api_field import ApiField
from .api_field_default_value import ApiFieldDefaultValue
from .api_field_edit_meta import ApiFieldEditMeta
from .api_field_meta import ApiFieldMeta
from .api_field_meta_date_time import ApiFieldMetaDateTime
from .api_field_meta_decimal import ApiFieldMetaDecimal
from .api_field_meta_dictionary import ApiFieldMetaDictionary
from .api_field_meta_dictionary_entry import ApiFieldMetaDictionaryEntry
from .api_field_meta_dictionary_multi_choice import ApiFieldMetaDictionaryMultiChoice
from .api_field_meta_execution_history import ApiFieldMetaExecutionHistory
from .api_field_meta_flag import ApiFieldMetaFlag
from .api_field_meta_id import ApiFieldMetaId
from .api_field_meta_sprint import ApiFieldMetaSprint
from .api_field_meta_string import ApiFieldMetaString
from .api_field_meta_string_auto_complete import ApiFieldMetaStringAutoComplete
from .api_field_meta_string_list import ApiFieldMetaStringList
from .api_field_meta_test_job_statistics import ApiFieldMetaTestJobStatistics
from .api_field_meta_test_scenarios import ApiFieldMetaTestScenarios
from .api_field_meta_time_span import ApiFieldMetaTimeSpan
from .api_field_meta_user import ApiFieldMetaUser
from .api_field_meta_user_multi_choice import ApiFieldMetaUserMultiChoice
from .api_field_patch_operation import ApiFieldPatchOperation
from .api_field_patch_operation_activate_field import ApiFieldPatchOperationActivateField
from .api_field_patch_operation_deactivate_field import ApiFieldPatchOperationDeactivateField
from .api_field_placeholder import ApiFieldPlaceholder
from .api_field_placeholders import ApiFieldPlaceholders
from .api_field_range import ApiFieldRange
from .api_field_rule import ApiFieldRule
from .api_field_rule_dependent_values import ApiFieldRuleDependentValues
from .api_field_rule_dependent_values_update import ApiFieldRuleDependentValuesUpdate
from .api_field_rule_update import ApiFieldRuleUpdate
from .api_field_rule_workflow import ApiFieldRuleWorkflow
from .api_field_rule_workflow_actions import ApiFieldRuleWorkflowActions
from .api_field_rule_workflow_actions_update import ApiFieldRuleWorkflowActionsUpdate
from .api_field_rule_workflow_transition import ApiFieldRuleWorkflowTransition
from .api_field_rule_workflow_transition_update import ApiFieldRuleWorkflowTransitionUpdate
from .api_field_rule_workflow_update import ApiFieldRuleWorkflowUpdate
from .api_field_rules import ApiFieldRules
from .api_field_rules_update import ApiFieldRulesUpdate
from .api_field_rules_update_with_item_type import ApiFieldRulesUpdateWithItemType
from .api_field_rules_with_ownership import ApiFieldRulesWithOwnership
from .api_field_sort_mode import ApiFieldSortMode
from .api_field_type import ApiFieldType
from .api_field_update import ApiFieldUpdate
from .api_field_value import ApiFieldValue
from .api_field_value_date_time import ApiFieldValueDateTime
from .api_field_value_decimal import ApiFieldValueDecimal
from .api_field_value_dictionary import ApiFieldValueDictionary
from .api_field_value_dictionary_multi_choice import ApiFieldValueDictionaryMultiChoice
from .api_field_value_execution_history import ApiFieldValueExecutionHistory
from .api_field_value_flag import ApiFieldValueFlag
from .api_field_value_id import ApiFieldValueId
from .api_field_value_json import ApiFieldValueJson
from .api_field_value_restriction import ApiFieldValueRestriction
from .api_field_value_restriction_update import ApiFieldValueRestrictionUpdate
from .api_field_value_rich_text import ApiFieldValueRichText
from .api_field_value_sprint import ApiFieldValueSprint
from .api_field_value_string import ApiFieldValueString
from .api_field_value_string_list import ApiFieldValueStringList
from .api_field_value_test_job_statistics import ApiFieldValueTestJobStatistics
from .api_field_value_test_scenarios import ApiFieldValueTestScenarios
from .api_field_value_time_span import ApiFieldValueTimeSpan
from .api_field_value_user import ApiFieldValueUser
from .api_field_value_user_multi_choice import ApiFieldValueUserMultiChoice
from .api_field_with_value import ApiFieldWithValue
from .api_file_upload_info import ApiFileUploadInfo
from .api_file_upload_url_request import ApiFileUploadUrlRequest
from .api_file_upload_url_response import ApiFileUploadUrlResponse
from .api_file_upload_url_type import ApiFileUploadUrlType
from .api_filter import ApiFilter
from .api_filter_update import ApiFilterUpdate
from .api_folder_notification_rule import ApiFolderNotificationRule
from .api_folder_notification_rule_patch_request import ApiFolderNotificationRulePatchRequest
from .api_folder_notification_rule_patch_types import ApiFolderNotificationRulePatchTypes
from .api_folder_notification_rule_replacement import ApiFolderNotificationRuleReplacement
from .api_folder_notification_rule_replacement_with_type import ApiFolderNotificationRuleReplacementWithType
from .api_folder_notification_rule_response import ApiFolderNotificationRuleResponse
from .api_forbidden_error import ApiForbiddenError
from .api_forbidden_error_type import ApiForbiddenErrorType
from .api_get_license_permissions_response import ApiGetLicensePermissionsResponse
from .api_get_license_response import ApiGetLicenseResponse
from .api_get_user_assignment_response import ApiGetUserAssignmentResponse
from .api_global_search_area import ApiGlobalSearchArea
from .api_global_search_item import ApiGlobalSearchItem
from .api_global_search_request import ApiGlobalSearchRequest
from .api_global_search_result import ApiGlobalSearchResult
from .api_grid_config import ApiGridConfig
from .api_grid_config_column import ApiGridConfigColumn
from .api_grid_config_column_fixed_position import ApiGridConfigColumnFixedPosition
from .api_grid_config_column_sort_group import ApiGridConfigColumnSortGroup
from .api_grid_config_column_sort_order import ApiGridConfigColumnSortOrder
from .api_history_attachments import ApiHistoryAttachments
from .api_history_automation import ApiHistoryAutomation
from .api_history_automation_modified import ApiHistoryAutomationModified
from .api_history_creation_mode import ApiHistoryCreationMode
from .api_history_dependency_change_type import ApiHistoryDependencyChangeType
from .api_history_dependency_changed import ApiHistoryDependencyChanged
from .api_history_enclosure_change_type import ApiHistoryEnclosureChangeType
from .api_history_enclosure_changed import ApiHistoryEnclosureChanged
from .api_history_entry import ApiHistoryEntry
from .api_history_entry_defect import ApiHistoryEntryDefect
from .api_history_entry_requirement import ApiHistoryEntryRequirement
from .api_history_entry_test_case import ApiHistoryEntryTestCase
from .api_history_entry_test_scenario import ApiHistoryEntryTestScenario
from .api_history_field_change_type import ApiHistoryFieldChangeType
from .api_history_field_changed import ApiHistoryFieldChanged
from .api_history_item_created import ApiHistoryItemCreated
from .api_history_item_migrated import ApiHistoryItemMigrated
from .api_history_item_moved import ApiHistoryItemMoved
from .api_history_post_change_type import ApiHistoryPostChangeType
from .api_history_post_changed import ApiHistoryPostChanged
from .api_history_script_file_modified import ApiHistoryScriptFileModified
from .api_history_subrequirements import ApiHistorySubrequirements
from .api_history_sync_event import ApiHistorySyncEvent
from .api_history_sync_event_type import ApiHistorySyncEventType
from .api_history_test_data import ApiHistoryTestData
from .api_history_test_job_modified import ApiHistoryTestJobModified
from .api_history_test_jobs import ApiHistoryTestJobs
from .api_history_test_step_modified import ApiHistoryTestStepModified
from .api_history_test_steps import ApiHistoryTestSteps
from .api_history_user_c_cs import ApiHistoryUserCCs
from .api_html_content_widget_data import ApiHtmlContentWidgetData
from .api_html_content_widget_data_specification import ApiHtmlContentWidgetDataSpecification
from .api_html_content_widget_model import ApiHtmlContentWidgetModel
from .api_image_info import ApiImageInfo
from .api_image_upload_info import ApiImageUploadInfo
from .api_import_error_report_item import ApiImportErrorReportItem
from .api_import_error_type import ApiImportErrorType
from .api_import_long_running_task_info import ApiImportLongRunningTaskInfo
from .api_import_phase import ApiImportPhase
from .api_import_project_template_preview_entry import ApiImportProjectTemplatePreviewEntry
from .api_import_project_template_preview_response import ApiImportProjectTemplatePreviewResponse
from .api_integration_config_base import ApiIntegrationConfigBase
from .api_integration_config_jira import ApiIntegrationConfigJira
from .api_integration_config_otrs import ApiIntegrationConfigOtrs
from .api_integration_config_update_base import ApiIntegrationConfigUpdateBase
from .api_integration_config_update_jira import ApiIntegrationConfigUpdateJira
from .api_integration_config_update_otrs import ApiIntegrationConfigUpdateOtrs
from .api_integration_config_verify_base import ApiIntegrationConfigVerifyBase
from .api_integration_config_verify_jira import ApiIntegrationConfigVerifyJira
from .api_integration_config_verify_otrs import ApiIntegrationConfigVerifyOtrs
from .api_integration_configurations import ApiIntegrationConfigurations
from .api_integration_configurations_update import ApiIntegrationConfigurationsUpdate
from .api_integration_enable import ApiIntegrationEnable
from .api_integration_verify_response import ApiIntegrationVerifyResponse
from .api_internal_error import ApiInternalError
from .api_intial_type import ApiIntialType
from .api_item import ApiItem
from .api_item_arrangement import ApiItemArrangement
from .api_item_arrangement_grouping import ApiItemArrangementGrouping
from .api_item_create_meta import ApiItemCreateMeta
from .api_item_edit_meta import ApiItemEditMeta
from .api_item_edit_status import ApiItemEditStatus
from .api_item_export_request import ApiItemExportRequest
from .api_item_group import ApiItemGroup
from .api_item_groups_result import ApiItemGroupsResult
from .api_item_identifier import ApiItemIdentifier
from .api_item_import_request import ApiItemImportRequest
from .api_item_info import ApiItemInfo
from .api_item_list_request import ApiItemListRequest
from .api_item_list_result import ApiItemListResult
from .api_item_list_widget_data import ApiItemListWidgetData
from .api_item_list_widget_data_specification import ApiItemListWidgetDataSpecification
from .api_item_list_widget_model import ApiItemListWidgetModel
from .api_item_list_widget_sorting import ApiItemListWidgetSorting
from .api_item_location import ApiItemLocation
from .api_item_location_update import ApiItemLocationUpdate
from .api_item_long_operation_archive import ApiItemLongOperationArchive
from .api_item_long_operation_copy_in_project import ApiItemLongOperationCopyInProject
from .api_item_long_operation_copy_to_project import ApiItemLongOperationCopyToProject
from .api_item_long_operation_delete import ApiItemLongOperationDelete
from .api_item_long_operation_domain import ApiItemLongOperationDomain
from .api_item_long_operation_domain_filter_based import ApiItemLongOperationDomainFilterBased
from .api_item_long_operation_domain_list_based import ApiItemLongOperationDomainListBased
from .api_item_long_operation_info import ApiItemLongOperationInfo
from .api_item_long_operation_move_in_project import ApiItemLongOperationMoveInProject
from .api_item_long_operation_update_properties import ApiItemLongOperationUpdateProperties
from .api_item_new import ApiItemNew
from .api_item_new_with_description import ApiItemNewWithDescription
from .api_item_new_with_enclosures import ApiItemNewWithEnclosures
from .api_item_new_with_test_data_and_test_steps import ApiItemNewWithTestDataAndTestSteps
from .api_item_new_with_test_jobs import ApiItemNewWithTestJobs
from .api_item_permissions import ApiItemPermissions
from .api_item_permissions_can_create_dependent_item import ApiItemPermissionsCanCreateDependentItem
from .api_item_search_result import ApiItemSearchResult
from .api_item_type import ApiItemType
from .api_item_type_is_web_layout_info import ApiItemTypeIsWebLayoutInfo
from .api_item_update import ApiItemUpdate
from .api_item_update_with_description import ApiItemUpdateWithDescription
from .api_item_update_with_enclosures import ApiItemUpdateWithEnclosures
from .api_item_update_with_test_data_and_test_steps import ApiItemUpdateWithTestDataAndTestSteps
from .api_item_update_with_test_jobs import ApiItemUpdateWithTestJobs
from .api_item_version import ApiItemVersion
from .api_item_with_description import ApiItemWithDescription
from .api_items_patch_request import ApiItemsPatchRequest
from .api_items_patch_request_archive import ApiItemsPatchRequestArchive
from .api_items_patch_request_copy_in_project import ApiItemsPatchRequestCopyInProject
from .api_items_patch_request_copy_to_project import ApiItemsPatchRequestCopyToProject
from .api_items_patch_request_delete import ApiItemsPatchRequestDelete
from .api_items_patch_request_move_in_project import ApiItemsPatchRequestMoveInProject
from .api_items_patch_request_update_properties import ApiItemsPatchRequestUpdateProperties
from .api_label import ApiLabel
from .api_label_attached import ApiLabelAttached
from .api_label_info import ApiLabelInfo
from .api_label_list_result import ApiLabelListResult
from .api_label_new import ApiLabelNew
from .api_label_new_response import ApiLabelNewResponse
from .api_label_reference import ApiLabelReference
from .api_label_update import ApiLabelUpdate
from .api_last_execution_info import ApiLastExecutionInfo
from .api_license import ApiLicense
from .api_license_info import ApiLicenseInfo
from .api_license_profile import ApiLicenseProfile
from .api_license_profile_utilization import ApiLicenseProfileUtilization
from .api_license_profile_utilization_info import ApiLicenseProfileUtilizationInfo
from .api_license_type import ApiLicenseType
from .api_lock_new import ApiLockNew
from .api_login_incident import ApiLoginIncident
from .api_login_incident_reason import ApiLoginIncidentReason
from .api_long_operation import ApiLongOperation
from .api_long_operation_info import ApiLongOperationInfo
from .api_long_operation_info_base import ApiLongOperationInfoBase
from .api_long_operation_of_boolean import ApiLongOperationOfBoolean
from .api_long_operation_of_integer import ApiLongOperationOfInteger
from .api_long_operation_patch_abort import ApiLongOperationPatchAbort
from .api_long_operation_patch_operation import ApiLongOperationPatchOperation
from .api_long_operation_status import ApiLongOperationStatus
from .api_media_type_not_supported_error import ApiMediaTypeNotSupportedError
from .api_method_not_allowed_error import ApiMethodNotAllowedError
from .api_my_user_info import ApiMyUserInfo
from .api_navigation_dependency_response import ApiNavigationDependencyResponse
from .api_nested_test_case_info import ApiNestedTestCaseInfo
from .api_nested_test_case_info_new import ApiNestedTestCaseInfoNew
from .api_nested_test_case_info_update import ApiNestedTestCaseInfoUpdate
from .api_nested_test_case_variables_inheritance import ApiNestedTestCaseVariablesInheritance
from .api_news_settings import ApiNewsSettings
from .api_not_found_error import ApiNotFoundError
from .api_notification_rule_filter_options import ApiNotificationRuleFilterOptions
from .api_notification_rule_filter_type import ApiNotificationRuleFilterType
from .api_operation_log import ApiOperationLog
from .api_operation_log_category import ApiOperationLogCategory
from .api_operation_log_category_scope import ApiOperationLogCategoryScope
from .api_paginated_result_of_api_item_info import ApiPaginatedResultOfApiItemInfo
from .api_paginated_result_of_api_login_incident import ApiPaginatedResultOfApiLoginIncident
from .api_paginated_result_of_api_test_execution_info import ApiPaginatedResultOfApiTestExecutionInfo
from .api_paginated_result_of_api_user_last_activity_info import ApiPaginatedResultOfApiUserLastActivityInfo
from .api_pdf_a_compatibility import ApiPdfACompatibility
from .api_pdf_changing_permissions import ApiPdfChangingPermissions
from .api_pdf_image_quality import ApiPdfImageQuality
from .api_pdf_password_security_options import ApiPdfPasswordSecurityOptions
from .api_pdf_permissions_options import ApiPdfPermissionsOptions
from .api_pdf_printing_permissions import ApiPdfPrintingPermissions
from .api_permission import ApiPermission
from .api_permission_dependencies_patch_response import ApiPermissionDependenciesPatchResponse
from .api_permission_result import ApiPermissionResult
from .api_pool import ApiPool
from .api_post import ApiPost
from .api_post_info import ApiPostInfo
from .api_post_paginated import ApiPostPaginated
from .api_project_config_info import ApiProjectConfigInfo
from .api_project_create import ApiProjectCreate
from .api_project_create_source import ApiProjectCreateSource
from .api_project_field_rules import ApiProjectFieldRules
from .api_project_field_rules_update import ApiProjectFieldRulesUpdate
from .api_project_folder import ApiProjectFolder
from .api_project_folder_create import ApiProjectFolderCreate
from .api_project_folder_create_source_folder import ApiProjectFolderCreateSourceFolder
from .api_project_folder_favourite import ApiProjectFolderFavourite
from .api_project_folder_favourite_new import ApiProjectFolderFavouriteNew
from .api_project_folder_favourite_patch import ApiProjectFolderFavouritePatch
from .api_project_folder_favourite_patch_rename import ApiProjectFolderFavouritePatchRename
from .api_project_folder_item_type_permissions import ApiProjectFolderItemTypePermissions
from .api_project_folder_patch_move import ApiProjectFolderPatchMove
from .api_project_folder_patch_operation import ApiProjectFolderPatchOperation
from .api_project_folder_patch_rename import ApiProjectFolderPatchRename
from .api_project_folder_permissions import ApiProjectFolderPermissions
from .api_project_id_name import ApiProjectIdName
from .api_project_id_name_has_subfolders import ApiProjectIdNameHasSubfolders
from .api_project_info import ApiProjectInfo
from .api_project_new_response import ApiProjectNewResponse
from .api_project_notification_rule import ApiProjectNotificationRule
from .api_project_notification_template import ApiProjectNotificationTemplate
from .api_project_notification_templates import ApiProjectNotificationTemplates
from .api_project_notification_type import ApiProjectNotificationType
from .api_project_options import ApiProjectOptions
from .api_project_options_with_ownership import ApiProjectOptionsWithOwnership
from .api_project_patch_archive import ApiProjectPatchArchive
from .api_project_patch_operation import ApiProjectPatchOperation
from .api_project_patch_rename import ApiProjectPatchRename
from .api_project_permissions import ApiProjectPermissions
from .api_project_sub_folder import ApiProjectSubFolder
from .api_project_subfolders_batch_create import ApiProjectSubfoldersBatchCreate
from .api_project_subfolders_patch_operation import ApiProjectSubfoldersPatchOperation
from .api_project_template_dictionary import ApiProjectTemplateDictionary
from .api_project_template_dictionary_entry import ApiProjectTemplateDictionaryEntry
from .api_project_template_dictionary_entry_new import ApiProjectTemplateDictionaryEntryNew
from .api_project_template_dictionary_new import ApiProjectTemplateDictionaryNew
from .api_project_template_dictionary_update import ApiProjectTemplateDictionaryUpdate
from .api_project_template_dictionary_usage import ApiProjectTemplateDictionaryUsage
from .api_project_template_dictionary_with_usage import ApiProjectTemplateDictionaryWithUsage
from .api_project_template_information import ApiProjectTemplateInformation
from .api_project_tree_folder import ApiProjectTreeFolder
from .api_project_tree_path_response import ApiProjectTreePathResponse
from .api_project_tree_project import ApiProjectTreeProject
from .api_project_tree_response import ApiProjectTreeResponse
from .api_project_update_project_folder_roles_request import ApiProjectUpdateProjectFolderRolesRequest
from .api_project_update_project_folder_roles_response import ApiProjectUpdateProjectFolderRolesResponse
from .api_redirect_result import ApiRedirectResult
from .api_registered_file_editor import ApiRegisteredFileEditor
from .api_registered_file_editors_repository import ApiRegisteredFileEditorsRepository
from .api_relation import ApiRelation
from .api_relation_create_meta import ApiRelationCreateMeta
from .api_relation_create_meta_allowed_types import ApiRelationCreateMetaAllowedTypes
from .api_relation_new import ApiRelationNew
from .api_relation_type import ApiRelationType
from .api_relations import ApiRelations
from .api_report_create_request import ApiReportCreateRequest
from .api_report_csv_printout_options import ApiReportCsvPrintoutOptions
from .api_report_definition_info import ApiReportDefinitionInfo
from .api_report_definition_patch_collection_operation import ApiReportDefinitionPatchCollectionOperation
from .api_report_definition_patch_collection_response import ApiReportDefinitionPatchCollectionResponse
from .api_report_definition_patch_copy_collection_operation import ApiReportDefinitionPatchCopyCollectionOperation
from .api_report_definition_patch_publish import ApiReportDefinitionPatchPublish
from .api_report_definition_patch_request import ApiReportDefinitionPatchRequest
from .api_report_definition_patch_unpublish import ApiReportDefinitionPatchUnpublish
from .api_report_docx_printout_document_options import ApiReportDocxPrintoutDocumentOptions
from .api_report_docx_printout_options import ApiReportDocxPrintoutOptions
from .api_report_file_type import ApiReportFileType
from .api_report_html_printout_options import ApiReportHtmlPrintoutOptions
from .api_report_image_printout_options import ApiReportImagePrintoutOptions
from .api_report_mht_printout_options import ApiReportMhtPrintoutOptions
from .api_report_options import ApiReportOptions
from .api_report_options_new import ApiReportOptionsNew
from .api_report_options_update import ApiReportOptionsUpdate
from .api_report_parameter import ApiReportParameter
from .api_report_parameter_type import ApiReportParameterType
from .api_report_parameter_value import ApiReportParameterValue
from .api_report_patch_import import ApiReportPatchImport
from .api_report_patch_operation import ApiReportPatchOperation
from .api_report_pdf_printout_document_options import ApiReportPdfPrintoutDocumentOptions
from .api_report_pdf_printout_options import ApiReportPdfPrintoutOptions
from .api_report_permissions import ApiReportPermissions
from .api_report_plugin import ApiReportPlugin
from .api_report_printout_default_boolean import ApiReportPrintoutDefaultBoolean
from .api_report_printout_export_image_type import ApiReportPrintoutExportImageType
from .api_report_printout_export_mode import ApiReportPrintoutExportMode
from .api_report_printout_request import ApiReportPrintoutRequest
from .api_report_printout_request_csv import ApiReportPrintoutRequestCsv
from .api_report_printout_request_docx import ApiReportPrintoutRequestDocx
from .api_report_printout_request_file import ApiReportPrintoutRequestFile
from .api_report_printout_request_html import ApiReportPrintoutRequestHtml
from .api_report_printout_request_image import ApiReportPrintoutRequestImage
from .api_report_printout_request_mht import ApiReportPrintoutRequestMht
from .api_report_printout_request_pdf import ApiReportPrintoutRequestPdf
from .api_report_printout_request_rtf import ApiReportPrintoutRequestRtf
from .api_report_printout_request_text import ApiReportPrintoutRequestText
from .api_report_printout_request_xls import ApiReportPrintoutRequestXls
from .api_report_printout_request_xlsx import ApiReportPrintoutRequestXlsx
from .api_report_printout_text_export_mode import ApiReportPrintoutTextExportMode
from .api_report_rtf_printout_options import ApiReportRtfPrintoutOptions
from .api_report_text_printout_options import ApiReportTextPrintoutOptions
from .api_report_workbook_color_palette_compliance import ApiReportWorkbookColorPaletteCompliance
from .api_report_xl_printout_document_options import ApiReportXlPrintoutDocumentOptions
from .api_report_xl_printout_encryption_options import ApiReportXlPrintoutEncryptionOptions
from .api_report_xls_printout_encryption_type import ApiReportXlsPrintoutEncryptionType
from .api_report_xls_printout_options import ApiReportXlsPrintoutOptions
from .api_report_xlsx_printout_options import ApiReportXlsxPrintoutOptions
from .api_requirement import ApiRequirement
from .api_requirement_report_allowed_options_update import ApiRequirementReportAllowedOptionsUpdate
from .api_requirement_report_options import ApiRequirementReportOptions
from .api_reset_password_result import ApiResetPasswordResult
from .api_reset_password_user import ApiResetPasswordUser
from .api_rich_text import ApiRichText
from .api_rich_text_include_type import ApiRichTextIncludeType
from .api_role import ApiRole
from .api_role_id_name import ApiRoleIdName
from .api_role_new import ApiRoleNew
from .api_role_new_response import ApiRoleNewResponse
from .api_role_patch_request import ApiRolePatchRequest
from .api_role_patch_request_replace_role import ApiRolePatchRequestReplaceRole
from .api_run_dependency_entry import ApiRunDependencyEntry
from .api_script import ApiScript
from .api_search_operation_log_result import ApiSearchOperationLogResult
from .api_single_agent import ApiSingleAgent
from .api_sprint import ApiSprint
from .api_sprint_new import ApiSprintNew
from .api_sprint_new_response import ApiSprintNewResponse
from .api_sprint_statistic import ApiSprintStatistic
from .api_sprint_update import ApiSprintUpdate
from .api_sprints_include import ApiSprintsInclude
from .api_subrequirement import ApiSubrequirement
from .api_subrequirement_new import ApiSubrequirementNew
from .api_subrequirement_update import ApiSubrequirementUpdate
from .api_subrequirements_new import ApiSubrequirementsNew
from .api_subrequirements_update import ApiSubrequirementsUpdate
from .api_sync_item_status import ApiSyncItemStatus
from .api_system_get_colors_response import ApiSystemGetColorsResponse
from .api_system_permissions import ApiSystemPermissions
from .api_system_settings import ApiSystemSettings
from .api_test_case import ApiTestCase
from .api_test_case_create_meta import ApiTestCaseCreateMeta
from .api_test_case_edit_meta import ApiTestCaseEditMeta
from .api_test_case_execution_defaults import ApiTestCaseExecutionDefaults
from .api_test_case_execution_defaults_base import ApiTestCaseExecutionDefaultsBase
from .api_test_case_execution_defaults_update import ApiTestCaseExecutionDefaultsUpdate
from .api_test_case_execution_history import ApiTestCaseExecutionHistory
from .api_test_case_execution_history_entry import ApiTestCaseExecutionHistoryEntry
from .api_test_case_execution_preview_request import ApiTestCaseExecutionPreviewRequest
from .api_test_case_execution_preview_response import ApiTestCaseExecutionPreviewResponse
from .api_test_case_job_info import ApiTestCaseJobInfo
from .api_test_case_report_allowed_options_update import ApiTestCaseReportAllowedOptionsUpdate
from .api_test_case_report_options import ApiTestCaseReportOptions
from .api_test_case_run_status import ApiTestCaseRunStatus
from .api_test_cases_have_steps_response import ApiTestCasesHaveStepsResponse
from .api_test_cases_have_steps_response_test_cases import ApiTestCasesHaveStepsResponseTestCases
from .api_test_data import ApiTestData
from .api_test_data_file_format import ApiTestDataFileFormat
from .api_test_data_local import ApiTestDataLocal
from .api_test_data_new import ApiTestDataNew
from .api_test_data_new_local import ApiTestDataNewLocal
from .api_test_data_new_referenced_test_case import ApiTestDataNewReferencedTestCase
from .api_test_data_new_value_set import ApiTestDataNewValueSet
from .api_test_data_new_variable import ApiTestDataNewVariable
from .api_test_data_preview import ApiTestDataPreview
from .api_test_data_referenced_test_case import ApiTestDataReferencedTestCase
from .api_test_data_referenced_value_set_info import ApiTestDataReferencedValueSetInfo
from .api_test_data_update import ApiTestDataUpdate
from .api_test_data_update_local import ApiTestDataUpdateLocal
from .api_test_data_update_referenced_test_case import ApiTestDataUpdateReferencedTestCase
from .api_test_data_update_value_set import ApiTestDataUpdateValueSet
from .api_test_data_update_variable import ApiTestDataUpdateVariable
from .api_test_data_value_set import ApiTestDataValueSet
from .api_test_data_value_set_info import ApiTestDataValueSetInfo
from .api_test_data_value_set_new import ApiTestDataValueSetNew
from .api_test_data_value_set_update import ApiTestDataValueSetUpdate
from .api_test_data_variable import ApiTestDataVariable
from .api_test_data_variable_with_value import ApiTestDataVariableWithValue
from .api_test_execution import ApiTestExecution
from .api_test_execution_continue_response import ApiTestExecutionContinueResponse
from .api_test_execution_create_lock import ApiTestExecutionCreateLock
from .api_test_execution_create_meta import ApiTestExecutionCreateMeta
from .api_test_execution_data_attribute import ApiTestExecutionDataAttribute
from .api_test_execution_data_attribute_type import ApiTestExecutionDataAttributeType
from .api_test_execution_extended_info import ApiTestExecutionExtendedInfo
from .api_test_execution_identifier import ApiTestExecutionIdentifier
from .api_test_execution_info import ApiTestExecutionInfo
from .api_test_execution_log import ApiTestExecutionLog
from .api_test_execution_log_user_entry_new import ApiTestExecutionLogUserEntryNew
from .api_test_execution_modifying_status import ApiTestExecutionModifyingStatus
from .api_test_execution_new import ApiTestExecutionNew
from .api_test_execution_new_response import ApiTestExecutionNewResponse
from .api_test_execution_new_response_test_case_context import ApiTestExecutionNewResponseTestCaseContext
from .api_test_execution_new_response_test_scenario_context import ApiTestExecutionNewResponseTestScenarioContext
from .api_test_execution_new_test_scenario_info import ApiTestExecutionNewTestScenarioInfo
from .api_test_execution_patch_cancel import ApiTestExecutionPatchCancel
from .api_test_execution_patch_finalize import ApiTestExecutionPatchFinalize
from .api_test_execution_patch_mark_irrelevant import ApiTestExecutionPatchMarkIrrelevant
from .api_test_execution_patch_mark_relevant import ApiTestExecutionPatchMarkRelevant
from .api_test_execution_patch_request import ApiTestExecutionPatchRequest
from .api_test_execution_patch_response import ApiTestExecutionPatchResponse
from .api_test_execution_permission import ApiTestExecutionPermission
from .api_test_execution_statistics import ApiTestExecutionStatistics
from .api_test_execution_status import ApiTestExecutionStatus
from .api_test_execution_test_scenario_info import ApiTestExecutionTestScenarioInfo
from .api_test_execution_type import ApiTestExecutionType
from .api_test_execution_update import ApiTestExecutionUpdate
from .api_test_execution_update_single import ApiTestExecutionUpdateSingle
from .api_test_job import ApiTestJob
from .api_test_job_details_update import ApiTestJobDetailsUpdate
from .api_test_job_new import ApiTestJobNew
from .api_test_job_preview import ApiTestJobPreview
from .api_test_job_preview_response import ApiTestJobPreviewResponse
from .api_test_job_statistics_entry import ApiTestJobStatisticsEntry
from .api_test_job_update import ApiTestJobUpdate
from .api_test_job_update_with_id import ApiTestJobUpdateWithId
from .api_test_jobs_update import ApiTestJobsUpdate
from .api_test_scenario import ApiTestScenario
from .api_test_scenario_execution_preview_request import ApiTestScenarioExecutionPreviewRequest
from .api_test_scenario_execution_preview_response import ApiTestScenarioExecutionPreviewResponse
from .api_test_scenario_execution_statistics import ApiTestScenarioExecutionStatistics
from .api_test_scenario_execution_statistics_response import ApiTestScenarioExecutionStatisticsResponse
from .api_test_scenario_report_allowed_options_update import ApiTestScenarioReportAllowedOptionsUpdate
from .api_test_scenario_report_options import ApiTestScenarioReportOptions
from .api_test_scenario_run_status import ApiTestScenarioRunStatus
from .api_test_step import ApiTestStep
from .api_test_step_base import ApiTestStepBase
from .api_test_step_execution import ApiTestStepExecution
from .api_test_step_execution_new import ApiTestStepExecutionNew
from .api_test_step_execution_status import ApiTestStepExecutionStatus
from .api_test_step_execution_step_type import ApiTestStepExecutionStepType
from .api_test_step_execution_update import ApiTestStepExecutionUpdate
from .api_test_step_execution_update_single_step import ApiTestStepExecutionUpdateSingleStep
from .api_test_step_execution_update_status import ApiTestStepExecutionUpdateStatus
from .api_test_step_new import ApiTestStepNew
from .api_test_step_type import ApiTestStepType
from .api_test_step_update import ApiTestStepUpdate
from .api_test_step_update_with_id import ApiTestStepUpdateWithId
from .api_test_steps_update import ApiTestStepsUpdate
from .api_unauthorized_error import ApiUnauthorizedError
from .api_update_project_folder_role import ApiUpdateProjectFolderRole
from .api_update_role import ApiUpdateRole
from .api_update_user import ApiUpdateUser
from .api_uploaded_file import ApiUploadedFile
from .api_user import ApiUser
from .api_user_info import ApiUserInfo
from .api_user_last_activity_info import ApiUserLastActivityInfo
from .api_user_license_assignment import ApiUserLicenseAssignment
from .api_user_license_assignment_change_license_type_patch_request import (
    ApiUserLicenseAssignmentChangeLicenseTypePatchRequest,
)
from .api_user_license_assignment_patch_request import ApiUserLicenseAssignmentPatchRequest
from .api_user_minimal_info import ApiUserMinimalInfo
from .api_user_new import ApiUserNew
from .api_user_new_reponse import ApiUserNewReponse
from .api_user_patch_operation import ApiUserPatchOperation
from .api_user_patch_position import ApiUserPatchPosition
from .api_user_patch_request import ApiUserPatchRequest
from .api_user_patch_request_activate_user import ApiUserPatchRequestActivateUser
from .api_user_patch_request_deactivate_user import ApiUserPatchRequestDeactivateUser
from .api_user_patch_request_password_reset import ApiUserPatchRequestPasswordReset
from .api_user_patch_request_set_server_administrator import ApiUserPatchRequestSetServerAdministrator
from .api_user_patch_request_set_user_password import ApiUserPatchRequestSetUserPassword
from .api_user_project_assignment import ApiUserProjectAssignment
from .api_user_project_folder_assignment import ApiUserProjectFolderAssignment
from .api_user_project_folder_assignment_patch_operation import ApiUserProjectFolderAssignmentPatchOperation
from .api_user_project_folder_assignment_patch_replace import ApiUserProjectFolderAssignmentPatchReplace
from .api_user_role import ApiUserRole
from .api_user_session_state import ApiUserSessionState
from .api_user_status import ApiUserStatus
from .api_user_view import ApiUserView
from .api_user_view_column_info import ApiUserViewColumnInfo
from .api_user_view_column_sort_group_info import ApiUserViewColumnSortGroupInfo
from .api_user_view_column_sort_group_update import ApiUserViewColumnSortGroupUpdate
from .api_user_view_column_update import ApiUserViewColumnUpdate
from .api_user_view_info import ApiUserViewInfo
from .api_user_view_new import ApiUserViewNew
from .api_user_view_new_response import ApiUserViewNewResponse
from .api_user_view_patch_collection_operation import ApiUserViewPatchCollectionOperation
from .api_user_view_patch_collection_response import ApiUserViewPatchCollectionResponse
from .api_user_view_patch_copy_collection_operation import ApiUserViewPatchCopyCollectionOperation
from .api_user_view_permissions import ApiUserViewPermissions
from .api_user_view_update import ApiUserViewUpdate
from .api_user_view_update_fields_data import ApiUserViewUpdateFieldsData
from .api_watcher_new import ApiWatcherNew
from .api_watchers_update import ApiWatchersUpdate
from .api_widget_data import ApiWidgetData
from .api_widget_model import ApiWidgetModel
from .api_wiki_links_settings import ApiWikiLinksSettings
from .api_wiki_links_settings_base_urls import ApiWikiLinksSettingsBaseUrls
from .api_workflow import ApiWorkflow
from .api_workflow_graph_model import ApiWorkflowGraphModel
from .api_workflow_graph_node_model import ApiWorkflowGraphNodeModel
from .api_workflow_graph_transition_model import ApiWorkflowGraphTransitionModel
from .api_workflow_node_model import ApiWorkflowNodeModel
from .api_workflow_transition_model import ApiWorkflowTransitionModel
from .api_xls_ignore_errors import ApiXlsIgnoreErrors
from .aqua_client_type import AquaClientType
from .authentication_header_value import AuthenticationHeaderValue
from .cache_control_header_value import CacheControlHeaderValue
from .content_disposition_header_value import ContentDispositionHeaderValue
from .content_range_header_value import ContentRangeHeaderValue
from .defect_add_attachment_multipart_data import DefectAddAttachmentMultipartData
from .entity_tag_header_value import EntityTagHeaderValue
from .file_upload_file_multipart_data import FileUploadFileMultipartData
from .generic_permission_info import GenericPermissionInfo
from .http_content import HttpContent
from .http_content_headers import HttpContentHeaders
from .http_method import HttpMethod
from .http_request_headers import HttpRequestHeaders
from .http_request_message import HttpRequestMessage
from .http_request_message_properties import HttpRequestMessageProperties
from .i_api_relation_item_extra import IApiRelationItemExtra
from .image_upload_image_multipart_data import ImageUploadImageMultipartData
from .key_value_pair_of_string_and_i_enumerable_of_string import KeyValuePairOfStringAndIEnumerableOfString
from .media_type_header_value import MediaTypeHeaderValue
from .media_type_with_quality_header_value import MediaTypeWithQualityHeaderValue
from .name_value_header_value import NameValueHeaderValue
from .name_value_with_parameters_header_value import NameValueWithParametersHeaderValue
from .object_type import ObjectType
from .pdf_encryption_level import PdfEncryptionLevel
from .permission import Permission
from .permission_scope import PermissionScope
from .permission_variant import PermissionVariant
from .product_header_value import ProductHeaderValue
from .product_info_header_value import ProductInfoHeaderValue
from .project_import_single_report_definition_multipart_data import ProjectImportSingleReportDefinitionMultipartData
from .project_meta_import_from_file_multipart_data import ProjectMetaImportFromFileMultipartData
from .project_notification_import_project_notification_templates_multipart_data import (
    ProjectNotificationImportProjectNotificationTemplatesMultipartData,
)
from .range_condition_header_value import RangeConditionHeaderValue
from .range_header_value import RangeHeaderValue
from .range_item_header_value import RangeItemHeaderValue
from .requirement_add_attachment_multipart_data import RequirementAddAttachmentMultipartData
from .script_add_attachment_multipart_data import ScriptAddAttachmentMultipartData
from .string_with_quality_header_value import StringWithQualityHeaderValue
from .system_change_user_photo_multipart_data import SystemChangeUserPhotoMultipartData
from .test_case_add_attachment_multipart_data import TestCaseAddAttachmentMultipartData
from .test_case_import_test_data_multipart_data import TestCaseImportTestDataMultipartData
from .test_case_import_test_data_without_save_multipart_data import TestCaseImportTestDataWithoutSaveMultipartData
from .test_execution_add_attachment_multipart_data import TestExecutionAddAttachmentMultipartData
from .test_scenario_add_attachment_multipart_data import TestScenarioAddAttachmentMultipartData
from .time_unit import TimeUnit
from .transfer_coding_header_value import TransferCodingHeaderValue
from .transfer_coding_with_quality_header_value import TransferCodingWithQualityHeaderValue
from .user_change_user_photo_multipart_data import UserChangeUserPhotoMultipartData
from .value_tuple_of_integer_and_string import ValueTupleOfIntegerAndString
from .version import Version
from .via_header_value import ViaHeaderValue
from .warning_header_value import WarningHeaderValue

__all__ = (
    "ApiAddSingleTestJobResponse",
    "ApiAddSingleTestStepResponse",
    "ApiAgentBase",
    "ApiAgentCreateCopySingleAgent",
    "ApiAgentCreateOperation",
    "ApiAgentCreatePool",
    "ApiAgentCreateSingleAgent",
    "ApiAgentExecutionStatus",
    "ApiAgentIdAndName",
    "ApiAgentPatchOperation",
    "ApiAgentPatchUpdatePool",
    "ApiAgentPatchUpdateSingleAgent",
    "ApiAgentSimpleStatus",
    "ApiAgileBacklog",
    "ApiAgileBacklogStatus",
    "ApiAgileReorderItemsRequest",
    "ApiAgileReorderItemsResponse",
    "ApiAgileReorderItemsResponseReorderedPriority",
    "ApiAgileSettings",
    "ApiAllowedOption",
    "ApiAquaClientType",
    "ApiArgumentError",
    "ApiArgumentErrorType",
    "ApiAttachmentInfo",
    "ApiAttachmentNew",
    "ApiAttachments",
    "ApiAutomatedTestCaseExecution",
    "ApiAutomatedTestScenarioExecutionRequest",
    "ApiAutomatedTestScenarioExecutionRequestAll",
    "ApiAutomatedTestScenarioExecutionRequestPartial",
    "ApiAutomatedTestScenarioExecutionResponse",
    "ApiAutomaticExecutionSupport",
    "ApiAutomation",
    "ApiAutomationAttachedScriptFileInfo",
    "ApiAutomationAttachedScriptFileNew",
    "ApiAutomationSave",
    "ApiAutomationScript",
    "ApiAutomationScriptDatabase",
    "ApiAutomationScriptDatabaseSave",
    "ApiAutomationScriptJenkins",
    "ApiAutomationScriptJenkinsSave",
    "ApiAutomationScriptJMeter",
    "ApiAutomationScriptJMeterSave",
    "ApiAutomationScriptNone",
    "ApiAutomationScriptNoneSave",
    "ApiAutomationScriptNotSupported",
    "ApiAutomationScriptNotSupportedSave",
    "ApiAutomationScriptPowerShell",
    "ApiAutomationScriptPowerShellSave",
    "ApiAutomationScriptQTP",
    "ApiAutomationScriptQTPSave",
    "ApiAutomationScriptRanorex",
    "ApiAutomationScriptRanorexSave",
    "ApiAutomationScriptSave",
    "ApiAutomationScriptShell",
    "ApiAutomationScriptShellSave",
    "ApiAutomationScriptSoapUI",
    "ApiAutomationScriptSoapUISave",
    "ApiAutomationScriptUFT",
    "ApiAutomationScriptUFTSave",
    "ApiAutomationScriptUnixShell",
    "ApiAutomationScriptUnixShellSave",
    "ApiAutomationScriptWithAttachedFiles",
    "ApiAutomationScriptWithAttachedFilesSave",
    "ApiAutomationTechnology",
    "ApiBackendNotAvailableError",
    "ApiBaseItemAccessibility",
    "ApiBaseObjectReportAllowedOptions",
    "ApiBaseObjectReportAllowedOptionsUpdate",
    "ApiBaseObjectReportOptions",
    "ApiBatchAllowedValuesRequest",
    "ApiBatchAllowedValuesResponse",
    "ApiBatchAllowedValuesResponseEntry",
    "ApiBatchFieldUpdate",
    "ApiBatchFieldUpdateMultiChoiceFieldDifferential",
    "ApiBatchFieldUpdateNewEnclosure",
    "ApiBatchFieldUpdateRegularField",
    "ApiBatchItemOperationIssue",
    "ApiBatchItemOperationIssueType",
    "ApiBatchItemUpdateFieldIssueDetails",
    "ApiBatchItemUpdateIssueDetails",
    "ApiBatchItemUpdateIssueDetailsBase",
    "ApiBatchItemUpdateIssueDetailsType",
    "ApiBatchOperation",
    "ApiBatchOperationType",
    "ApiBulkExecutionsRequest",
    "ApiChartType",
    "ApiChartWidgetData",
    "ApiChartWidgetDataOneDimensionalElement",
    "ApiChartWidgetDataSpecification",
    "ApiChartWidgetDataStatus",
    "ApiChartWidgetDataTwoDimensionalElement",
    "ApiChartWidgetDateTimeScale",
    "ApiChartWidgetKPICondition",
    "ApiChartWidgetKPIEntry",
    "ApiChartWidgetModel",
    "ApiColumnSortOrder",
    "ApiConfigElement",
    "ApiConfigElementBase",
    "ApiConfigElementEntry",
    "ApiConfigElementEntrySave",
    "ApiConfigElementPatchOperation",
    "ApiConfigElementPatchOperationDelete",
    "ApiConfigElementSave",
    "ApiCreateLoginLinkResponse",
    "ApiCurrentlyExecutedStepInfo",
    "ApiCustomizedStrings",
    "ApiCustomizedStringsEnglish",
    "ApiCustomizedStringsGerman",
    "ApiCustomNotificationNew",
    "ApiDashboardNG",
    "ApiDashboardNGReorderWidgets",
    "ApiDashboardNGShareProject",
    "ApiDashboardNGSize",
    "ApiDashboardNGWidget",
    "ApiDashboardNGWidgetBinding",
    "ApiDefect",
    "ApiDefectReportAllowedOptionsUpdate",
    "ApiDefectReportOptions",
    "ApiDeleteProjectFolderRole",
    "ApiDependenciesAddPermissionPatchResponse",
    "ApiDependenciesAddSinglePermissionPatchRequest",
    "ApiDependenciesPermissionPatchRequest",
    "ApiDependenciesPermissionSetPatchRequest",
    "ApiDependenciesPermissionSetPatchResponse",
    "ApiDependenciesRemovePermissionPatchResponse",
    "ApiDependenciesRemoveSinglePermissionPatchRequest",
    "ApiDependencyType",
    "ApiDiffCategoryType",
    "ApiEditableInfo",
    "ApiEditableStatus",
    "ApiEditLayout",
    "ApiEditLayoutEntry",
    "ApiEditLayoutEntryField",
    "ApiEditLayoutEntryGroup",
    "ApiEditStatus",
    "ApiEnclosure",
    "ApiEnclosurePermissions",
    "ApiEnclosuresUpdate",
    "ApiEnclosureType",
    "ApiEnclosureUpdate",
    "ApiEnclosureUpdateWithId",
    "ApiEnvironmentInfo",
    "ApiError",
    "ApiErrorInformation",
    "ApiExecutionLogMessageType",
    "ApiExportLongRunningTaskInfo",
    "ApiExternalInfo",
    "ApiFeatureInfo",
    "ApiField",
    "ApiFieldDefaultValue",
    "ApiFieldEditMeta",
    "ApiFieldMeta",
    "ApiFieldMetaDateTime",
    "ApiFieldMetaDecimal",
    "ApiFieldMetaDictionary",
    "ApiFieldMetaDictionaryEntry",
    "ApiFieldMetaDictionaryMultiChoice",
    "ApiFieldMetaExecutionHistory",
    "ApiFieldMetaFlag",
    "ApiFieldMetaId",
    "ApiFieldMetaSprint",
    "ApiFieldMetaString",
    "ApiFieldMetaStringAutoComplete",
    "ApiFieldMetaStringList",
    "ApiFieldMetaTestJobStatistics",
    "ApiFieldMetaTestScenarios",
    "ApiFieldMetaTimeSpan",
    "ApiFieldMetaUser",
    "ApiFieldMetaUserMultiChoice",
    "ApiFieldPatchOperation",
    "ApiFieldPatchOperationActivateField",
    "ApiFieldPatchOperationDeactivateField",
    "ApiFieldPlaceholder",
    "ApiFieldPlaceholders",
    "ApiFieldRange",
    "ApiFieldRule",
    "ApiFieldRuleDependentValues",
    "ApiFieldRuleDependentValuesUpdate",
    "ApiFieldRules",
    "ApiFieldRulesUpdate",
    "ApiFieldRulesUpdateWithItemType",
    "ApiFieldRulesWithOwnership",
    "ApiFieldRuleUpdate",
    "ApiFieldRuleWorkflow",
    "ApiFieldRuleWorkflowActions",
    "ApiFieldRuleWorkflowActionsUpdate",
    "ApiFieldRuleWorkflowTransition",
    "ApiFieldRuleWorkflowTransitionUpdate",
    "ApiFieldRuleWorkflowUpdate",
    "ApiFieldSortMode",
    "ApiFieldType",
    "ApiFieldUpdate",
    "ApiFieldValue",
    "ApiFieldValueDateTime",
    "ApiFieldValueDecimal",
    "ApiFieldValueDictionary",
    "ApiFieldValueDictionaryMultiChoice",
    "ApiFieldValueExecutionHistory",
    "ApiFieldValueFlag",
    "ApiFieldValueId",
    "ApiFieldValueJson",
    "ApiFieldValueRestriction",
    "ApiFieldValueRestrictionUpdate",
    "ApiFieldValueRichText",
    "ApiFieldValueSprint",
    "ApiFieldValueString",
    "ApiFieldValueStringList",
    "ApiFieldValueTestJobStatistics",
    "ApiFieldValueTestScenarios",
    "ApiFieldValueTimeSpan",
    "ApiFieldValueUser",
    "ApiFieldValueUserMultiChoice",
    "ApiFieldWithValue",
    "ApiFileUploadInfo",
    "ApiFileUploadUrlRequest",
    "ApiFileUploadUrlResponse",
    "ApiFileUploadUrlType",
    "ApiFilter",
    "ApiFilterUpdate",
    "ApiFolderNotificationRule",
    "ApiFolderNotificationRulePatchRequest",
    "ApiFolderNotificationRulePatchTypes",
    "ApiFolderNotificationRuleReplacement",
    "ApiFolderNotificationRuleReplacementWithType",
    "ApiFolderNotificationRuleResponse",
    "ApiForbiddenError",
    "ApiForbiddenErrorType",
    "ApiGetLicensePermissionsResponse",
    "ApiGetLicenseResponse",
    "ApiGetUserAssignmentResponse",
    "ApiGlobalSearchArea",
    "ApiGlobalSearchItem",
    "ApiGlobalSearchRequest",
    "ApiGlobalSearchResult",
    "ApiGridConfig",
    "ApiGridConfigColumn",
    "ApiGridConfigColumnFixedPosition",
    "ApiGridConfigColumnSortGroup",
    "ApiGridConfigColumnSortOrder",
    "ApiHistoryAttachments",
    "ApiHistoryAutomation",
    "ApiHistoryAutomationModified",
    "ApiHistoryCreationMode",
    "ApiHistoryDependencyChanged",
    "ApiHistoryDependencyChangeType",
    "ApiHistoryEnclosureChanged",
    "ApiHistoryEnclosureChangeType",
    "ApiHistoryEntry",
    "ApiHistoryEntryDefect",
    "ApiHistoryEntryRequirement",
    "ApiHistoryEntryTestCase",
    "ApiHistoryEntryTestScenario",
    "ApiHistoryFieldChanged",
    "ApiHistoryFieldChangeType",
    "ApiHistoryItemCreated",
    "ApiHistoryItemMigrated",
    "ApiHistoryItemMoved",
    "ApiHistoryPostChanged",
    "ApiHistoryPostChangeType",
    "ApiHistoryScriptFileModified",
    "ApiHistorySubrequirements",
    "ApiHistorySyncEvent",
    "ApiHistorySyncEventType",
    "ApiHistoryTestData",
    "ApiHistoryTestJobModified",
    "ApiHistoryTestJobs",
    "ApiHistoryTestStepModified",
    "ApiHistoryTestSteps",
    "ApiHistoryUserCCs",
    "ApiHtmlContentWidgetData",
    "ApiHtmlContentWidgetDataSpecification",
    "ApiHtmlContentWidgetModel",
    "ApiImageInfo",
    "ApiImageUploadInfo",
    "ApiImportErrorReportItem",
    "ApiImportErrorType",
    "ApiImportLongRunningTaskInfo",
    "ApiImportPhase",
    "ApiImportProjectTemplatePreviewEntry",
    "ApiImportProjectTemplatePreviewResponse",
    "ApiIntegrationConfigBase",
    "ApiIntegrationConfigJira",
    "ApiIntegrationConfigOtrs",
    "ApiIntegrationConfigUpdateBase",
    "ApiIntegrationConfigUpdateJira",
    "ApiIntegrationConfigUpdateOtrs",
    "ApiIntegrationConfigurations",
    "ApiIntegrationConfigurationsUpdate",
    "ApiIntegrationConfigVerifyBase",
    "ApiIntegrationConfigVerifyJira",
    "ApiIntegrationConfigVerifyOtrs",
    "ApiIntegrationEnable",
    "ApiIntegrationVerifyResponse",
    "ApiInternalError",
    "ApiIntialType",
    "ApiItem",
    "ApiItemArrangement",
    "ApiItemArrangementGrouping",
    "ApiItemCreateMeta",
    "ApiItemEditMeta",
    "ApiItemEditStatus",
    "ApiItemExportRequest",
    "ApiItemGroup",
    "ApiItemGroupsResult",
    "ApiItemIdentifier",
    "ApiItemImportRequest",
    "ApiItemInfo",
    "ApiItemListRequest",
    "ApiItemListResult",
    "ApiItemListWidgetData",
    "ApiItemListWidgetDataSpecification",
    "ApiItemListWidgetModel",
    "ApiItemListWidgetSorting",
    "ApiItemLocation",
    "ApiItemLocationUpdate",
    "ApiItemLongOperationArchive",
    "ApiItemLongOperationCopyInProject",
    "ApiItemLongOperationCopyToProject",
    "ApiItemLongOperationDelete",
    "ApiItemLongOperationDomain",
    "ApiItemLongOperationDomainFilterBased",
    "ApiItemLongOperationDomainListBased",
    "ApiItemLongOperationInfo",
    "ApiItemLongOperationMoveInProject",
    "ApiItemLongOperationUpdateProperties",
    "ApiItemNew",
    "ApiItemNewWithDescription",
    "ApiItemNewWithEnclosures",
    "ApiItemNewWithTestDataAndTestSteps",
    "ApiItemNewWithTestJobs",
    "ApiItemPermissions",
    "ApiItemPermissionsCanCreateDependentItem",
    "ApiItemSearchResult",
    "ApiItemsPatchRequest",
    "ApiItemsPatchRequestArchive",
    "ApiItemsPatchRequestCopyInProject",
    "ApiItemsPatchRequestCopyToProject",
    "ApiItemsPatchRequestDelete",
    "ApiItemsPatchRequestMoveInProject",
    "ApiItemsPatchRequestUpdateProperties",
    "ApiItemType",
    "ApiItemTypeIsWebLayoutInfo",
    "ApiItemUpdate",
    "ApiItemUpdateWithDescription",
    "ApiItemUpdateWithEnclosures",
    "ApiItemUpdateWithTestDataAndTestSteps",
    "ApiItemUpdateWithTestJobs",
    "ApiItemVersion",
    "ApiItemWithDescription",
    "ApiLabel",
    "ApiLabelAttached",
    "ApiLabelInfo",
    "ApiLabelListResult",
    "ApiLabelNew",
    "ApiLabelNewResponse",
    "ApiLabelReference",
    "ApiLabelUpdate",
    "ApiLastExecutionInfo",
    "ApiLicense",
    "ApiLicenseInfo",
    "ApiLicenseProfile",
    "ApiLicenseProfileUtilization",
    "ApiLicenseProfileUtilizationInfo",
    "ApiLicenseType",
    "ApiLockNew",
    "ApiLoginIncident",
    "ApiLoginIncidentReason",
    "ApiLongOperation",
    "ApiLongOperationInfo",
    "ApiLongOperationInfoBase",
    "ApiLongOperationOfBoolean",
    "ApiLongOperationOfInteger",
    "ApiLongOperationPatchAbort",
    "ApiLongOperationPatchOperation",
    "ApiLongOperationStatus",
    "ApiMediaTypeNotSupportedError",
    "ApiMethodNotAllowedError",
    "ApiMyUserInfo",
    "ApiNavigationDependencyResponse",
    "ApiNestedTestCaseInfo",
    "ApiNestedTestCaseInfoNew",
    "ApiNestedTestCaseInfoUpdate",
    "ApiNestedTestCaseVariablesInheritance",
    "ApiNewsSettings",
    "ApiNotFoundError",
    "ApiNotificationRuleFilterOptions",
    "ApiNotificationRuleFilterType",
    "ApiOperationLog",
    "ApiOperationLogCategory",
    "ApiOperationLogCategoryScope",
    "ApiPaginatedResultOfApiItemInfo",
    "ApiPaginatedResultOfApiLoginIncident",
    "ApiPaginatedResultOfApiTestExecutionInfo",
    "ApiPaginatedResultOfApiUserLastActivityInfo",
    "ApiPdfACompatibility",
    "ApiPdfChangingPermissions",
    "ApiPdfImageQuality",
    "ApiPdfPasswordSecurityOptions",
    "ApiPdfPermissionsOptions",
    "ApiPdfPrintingPermissions",
    "ApiPermission",
    "ApiPermissionDependenciesPatchResponse",
    "ApiPermissionResult",
    "ApiPool",
    "ApiPost",
    "ApiPostInfo",
    "ApiPostPaginated",
    "ApiProjectConfigInfo",
    "ApiProjectCreate",
    "ApiProjectCreateSource",
    "ApiProjectFieldRules",
    "ApiProjectFieldRulesUpdate",
    "ApiProjectFolder",
    "ApiProjectFolderCreate",
    "ApiProjectFolderCreateSourceFolder",
    "ApiProjectFolderFavourite",
    "ApiProjectFolderFavouriteNew",
    "ApiProjectFolderFavouritePatch",
    "ApiProjectFolderFavouritePatchRename",
    "ApiProjectFolderItemTypePermissions",
    "ApiProjectFolderPatchMove",
    "ApiProjectFolderPatchOperation",
    "ApiProjectFolderPatchRename",
    "ApiProjectFolderPermissions",
    "ApiProjectIdName",
    "ApiProjectIdNameHasSubfolders",
    "ApiProjectInfo",
    "ApiProjectNewResponse",
    "ApiProjectNotificationRule",
    "ApiProjectNotificationTemplate",
    "ApiProjectNotificationTemplates",
    "ApiProjectNotificationType",
    "ApiProjectOptions",
    "ApiProjectOptionsWithOwnership",
    "ApiProjectPatchArchive",
    "ApiProjectPatchOperation",
    "ApiProjectPatchRename",
    "ApiProjectPermissions",
    "ApiProjectSubFolder",
    "ApiProjectSubfoldersBatchCreate",
    "ApiProjectSubfoldersPatchOperation",
    "ApiProjectTemplateDictionary",
    "ApiProjectTemplateDictionaryEntry",
    "ApiProjectTemplateDictionaryEntryNew",
    "ApiProjectTemplateDictionaryNew",
    "ApiProjectTemplateDictionaryUpdate",
    "ApiProjectTemplateDictionaryUsage",
    "ApiProjectTemplateDictionaryWithUsage",
    "ApiProjectTemplateInformation",
    "ApiProjectTreeFolder",
    "ApiProjectTreePathResponse",
    "ApiProjectTreeProject",
    "ApiProjectTreeResponse",
    "ApiProjectUpdateProjectFolderRolesRequest",
    "ApiProjectUpdateProjectFolderRolesResponse",
    "ApiRedirectResult",
    "ApiRegisteredFileEditor",
    "ApiRegisteredFileEditorsRepository",
    "ApiRelation",
    "ApiRelationCreateMeta",
    "ApiRelationCreateMetaAllowedTypes",
    "ApiRelationNew",
    "ApiRelations",
    "ApiRelationType",
    "ApiReportCreateRequest",
    "ApiReportCsvPrintoutOptions",
    "ApiReportDefinitionInfo",
    "ApiReportDefinitionPatchCollectionOperation",
    "ApiReportDefinitionPatchCollectionResponse",
    "ApiReportDefinitionPatchCopyCollectionOperation",
    "ApiReportDefinitionPatchPublish",
    "ApiReportDefinitionPatchRequest",
    "ApiReportDefinitionPatchUnpublish",
    "ApiReportDocxPrintoutDocumentOptions",
    "ApiReportDocxPrintoutOptions",
    "ApiReportFileType",
    "ApiReportHtmlPrintoutOptions",
    "ApiReportImagePrintoutOptions",
    "ApiReportMhtPrintoutOptions",
    "ApiReportOptions",
    "ApiReportOptionsNew",
    "ApiReportOptionsUpdate",
    "ApiReportParameter",
    "ApiReportParameterType",
    "ApiReportParameterValue",
    "ApiReportPatchImport",
    "ApiReportPatchOperation",
    "ApiReportPdfPrintoutDocumentOptions",
    "ApiReportPdfPrintoutOptions",
    "ApiReportPermissions",
    "ApiReportPlugin",
    "ApiReportPrintoutDefaultBoolean",
    "ApiReportPrintoutExportImageType",
    "ApiReportPrintoutExportMode",
    "ApiReportPrintoutRequest",
    "ApiReportPrintoutRequestCsv",
    "ApiReportPrintoutRequestDocx",
    "ApiReportPrintoutRequestFile",
    "ApiReportPrintoutRequestHtml",
    "ApiReportPrintoutRequestImage",
    "ApiReportPrintoutRequestMht",
    "ApiReportPrintoutRequestPdf",
    "ApiReportPrintoutRequestRtf",
    "ApiReportPrintoutRequestText",
    "ApiReportPrintoutRequestXls",
    "ApiReportPrintoutRequestXlsx",
    "ApiReportPrintoutTextExportMode",
    "ApiReportRtfPrintoutOptions",
    "ApiReportTextPrintoutOptions",
    "ApiReportWorkbookColorPaletteCompliance",
    "ApiReportXlPrintoutDocumentOptions",
    "ApiReportXlPrintoutEncryptionOptions",
    "ApiReportXlsPrintoutEncryptionType",
    "ApiReportXlsPrintoutOptions",
    "ApiReportXlsxPrintoutOptions",
    "ApiRequirement",
    "ApiRequirementReportAllowedOptionsUpdate",
    "ApiRequirementReportOptions",
    "ApiResetPasswordResult",
    "ApiResetPasswordUser",
    "ApiRichText",
    "ApiRichTextIncludeType",
    "ApiRole",
    "ApiRoleIdName",
    "ApiRoleNew",
    "ApiRoleNewResponse",
    "ApiRolePatchRequest",
    "ApiRolePatchRequestReplaceRole",
    "ApiRunDependencyEntry",
    "ApiScript",
    "ApiSearchOperationLogResult",
    "ApiSingleAgent",
    "ApiSprint",
    "ApiSprintNew",
    "ApiSprintNewResponse",
    "ApiSprintsInclude",
    "ApiSprintStatistic",
    "ApiSprintUpdate",
    "ApiSubrequirement",
    "ApiSubrequirementNew",
    "ApiSubrequirementsNew",
    "ApiSubrequirementsUpdate",
    "ApiSubrequirementUpdate",
    "ApiSyncItemStatus",
    "ApiSystemGetColorsResponse",
    "ApiSystemPermissions",
    "ApiSystemSettings",
    "ApiTestCase",
    "ApiTestCaseCreateMeta",
    "ApiTestCaseEditMeta",
    "ApiTestCaseExecutionDefaults",
    "ApiTestCaseExecutionDefaultsBase",
    "ApiTestCaseExecutionDefaultsUpdate",
    "ApiTestCaseExecutionHistory",
    "ApiTestCaseExecutionHistoryEntry",
    "ApiTestCaseExecutionPreviewRequest",
    "ApiTestCaseExecutionPreviewResponse",
    "ApiTestCaseJobInfo",
    "ApiTestCaseReportAllowedOptionsUpdate",
    "ApiTestCaseReportOptions",
    "ApiTestCaseRunStatus",
    "ApiTestCasesHaveStepsResponse",
    "ApiTestCasesHaveStepsResponseTestCases",
    "ApiTestData",
    "ApiTestDataFileFormat",
    "ApiTestDataLocal",
    "ApiTestDataNew",
    "ApiTestDataNewLocal",
    "ApiTestDataNewReferencedTestCase",
    "ApiTestDataNewValueSet",
    "ApiTestDataNewVariable",
    "ApiTestDataPreview",
    "ApiTestDataReferencedTestCase",
    "ApiTestDataReferencedValueSetInfo",
    "ApiTestDataUpdate",
    "ApiTestDataUpdateLocal",
    "ApiTestDataUpdateReferencedTestCase",
    "ApiTestDataUpdateValueSet",
    "ApiTestDataUpdateVariable",
    "ApiTestDataValueSet",
    "ApiTestDataValueSetInfo",
    "ApiTestDataValueSetNew",
    "ApiTestDataValueSetUpdate",
    "ApiTestDataVariable",
    "ApiTestDataVariableWithValue",
    "ApiTestExecution",
    "ApiTestExecutionContinueResponse",
    "ApiTestExecutionCreateLock",
    "ApiTestExecutionCreateMeta",
    "ApiTestExecutionDataAttribute",
    "ApiTestExecutionDataAttributeType",
    "ApiTestExecutionExtendedInfo",
    "ApiTestExecutionIdentifier",
    "ApiTestExecutionInfo",
    "ApiTestExecutionLog",
    "ApiTestExecutionLogUserEntryNew",
    "ApiTestExecutionModifyingStatus",
    "ApiTestExecutionNew",
    "ApiTestExecutionNewResponse",
    "ApiTestExecutionNewResponseTestCaseContext",
    "ApiTestExecutionNewResponseTestScenarioContext",
    "ApiTestExecutionNewTestScenarioInfo",
    "ApiTestExecutionPatchCancel",
    "ApiTestExecutionPatchFinalize",
    "ApiTestExecutionPatchMarkIrrelevant",
    "ApiTestExecutionPatchMarkRelevant",
    "ApiTestExecutionPatchRequest",
    "ApiTestExecutionPatchResponse",
    "ApiTestExecutionPermission",
    "ApiTestExecutionStatistics",
    "ApiTestExecutionStatus",
    "ApiTestExecutionTestScenarioInfo",
    "ApiTestExecutionType",
    "ApiTestExecutionUpdate",
    "ApiTestExecutionUpdateSingle",
    "ApiTestJob",
    "ApiTestJobDetailsUpdate",
    "ApiTestJobNew",
    "ApiTestJobPreview",
    "ApiTestJobPreviewResponse",
    "ApiTestJobStatisticsEntry",
    "ApiTestJobsUpdate",
    "ApiTestJobUpdate",
    "ApiTestJobUpdateWithId",
    "ApiTestScenario",
    "ApiTestScenarioExecutionPreviewRequest",
    "ApiTestScenarioExecutionPreviewResponse",
    "ApiTestScenarioExecutionStatistics",
    "ApiTestScenarioExecutionStatisticsResponse",
    "ApiTestScenarioReportAllowedOptionsUpdate",
    "ApiTestScenarioReportOptions",
    "ApiTestScenarioRunStatus",
    "ApiTestStep",
    "ApiTestStepBase",
    "ApiTestStepExecution",
    "ApiTestStepExecutionNew",
    "ApiTestStepExecutionStatus",
    "ApiTestStepExecutionStepType",
    "ApiTestStepExecutionUpdate",
    "ApiTestStepExecutionUpdateSingleStep",
    "ApiTestStepExecutionUpdateStatus",
    "ApiTestStepNew",
    "ApiTestStepsUpdate",
    "ApiTestStepType",
    "ApiTestStepUpdate",
    "ApiTestStepUpdateWithId",
    "ApiUnauthorizedError",
    "ApiUpdateProjectFolderRole",
    "ApiUpdateRole",
    "ApiUpdateUser",
    "ApiUploadedFile",
    "ApiUser",
    "ApiUserInfo",
    "ApiUserLastActivityInfo",
    "ApiUserLicenseAssignment",
    "ApiUserLicenseAssignmentChangeLicenseTypePatchRequest",
    "ApiUserLicenseAssignmentPatchRequest",
    "ApiUserMinimalInfo",
    "ApiUserNew",
    "ApiUserNewReponse",
    "ApiUserPatchOperation",
    "ApiUserPatchPosition",
    "ApiUserPatchRequest",
    "ApiUserPatchRequestActivateUser",
    "ApiUserPatchRequestDeactivateUser",
    "ApiUserPatchRequestPasswordReset",
    "ApiUserPatchRequestSetServerAdministrator",
    "ApiUserPatchRequestSetUserPassword",
    "ApiUserProjectAssignment",
    "ApiUserProjectFolderAssignment",
    "ApiUserProjectFolderAssignmentPatchOperation",
    "ApiUserProjectFolderAssignmentPatchReplace",
    "ApiUserRole",
    "ApiUserSessionState",
    "ApiUserStatus",
    "ApiUserView",
    "ApiUserViewColumnInfo",
    "ApiUserViewColumnSortGroupInfo",
    "ApiUserViewColumnSortGroupUpdate",
    "ApiUserViewColumnUpdate",
    "ApiUserViewInfo",
    "ApiUserViewNew",
    "ApiUserViewNewResponse",
    "ApiUserViewPatchCollectionOperation",
    "ApiUserViewPatchCollectionResponse",
    "ApiUserViewPatchCopyCollectionOperation",
    "ApiUserViewPermissions",
    "ApiUserViewUpdate",
    "ApiUserViewUpdateFieldsData",
    "ApiWatcherNew",
    "ApiWatchersUpdate",
    "ApiWidgetData",
    "ApiWidgetModel",
    "ApiWikiLinksSettings",
    "ApiWikiLinksSettingsBaseUrls",
    "ApiWorkflow",
    "ApiWorkflowGraphModel",
    "ApiWorkflowGraphNodeModel",
    "ApiWorkflowGraphTransitionModel",
    "ApiWorkflowNodeModel",
    "ApiWorkflowTransitionModel",
    "ApiXlsIgnoreErrors",
    "AquaClientType",
    "AuthenticationHeaderValue",
    "CacheControlHeaderValue",
    "ContentDispositionHeaderValue",
    "ContentRangeHeaderValue",
    "DefectAddAttachmentMultipartData",
    "EntityTagHeaderValue",
    "FileUploadFileMultipartData",
    "GenericPermissionInfo",
    "HttpContent",
    "HttpContentHeaders",
    "HttpMethod",
    "HttpRequestHeaders",
    "HttpRequestMessage",
    "HttpRequestMessageProperties",
    "IApiRelationItemExtra",
    "ImageUploadImageMultipartData",
    "KeyValuePairOfStringAndIEnumerableOfString",
    "MediaTypeHeaderValue",
    "MediaTypeWithQualityHeaderValue",
    "NameValueHeaderValue",
    "NameValueWithParametersHeaderValue",
    "ObjectType",
    "PdfEncryptionLevel",
    "Permission",
    "PermissionScope",
    "PermissionVariant",
    "ProductHeaderValue",
    "ProductInfoHeaderValue",
    "ProjectImportSingleReportDefinitionMultipartData",
    "ProjectMetaImportFromFileMultipartData",
    "ProjectNotificationImportProjectNotificationTemplatesMultipartData",
    "RangeConditionHeaderValue",
    "RangeHeaderValue",
    "RangeItemHeaderValue",
    "RequirementAddAttachmentMultipartData",
    "ScriptAddAttachmentMultipartData",
    "StringWithQualityHeaderValue",
    "SystemChangeUserPhotoMultipartData",
    "TestCaseAddAttachmentMultipartData",
    "TestCaseImportTestDataMultipartData",
    "TestCaseImportTestDataWithoutSaveMultipartData",
    "TestExecutionAddAttachmentMultipartData",
    "TestScenarioAddAttachmentMultipartData",
    "TimeUnit",
    "TransferCodingHeaderValue",
    "TransferCodingWithQualityHeaderValue",
    "UserChangeUserPhotoMultipartData",
    "ValueTupleOfIntegerAndString",
    "Version",
    "ViaHeaderValue",
    "WarningHeaderValue",
)
